channels:
- conda-forge
dependencies:
- python=3.11.2
- pip<=23.0.1
- pip:
  - mlflow==2.17.0
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - psutil==6.0.0
  - scikit-learn==1.4.2
  - scipy==1.11.4
name: mlflow-env
